apiVersion: apps/v1
kind: Deployment

metadata:
  name: fake-job-detector

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fake-job-detector

  template:
    metadata:
      labels:
        app: fake-job-detector

    spec:
      containers:
        - name: fake-job-detector

          image: 731976569576.dkr.ecr.us-east-1.amazonaws.com/fake-job-detector:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000